description: efficientnet
runner: r004
device: cuda
batch_size: 32
max_epoch: 50
fobj: ce
dlt_bias: false
dlt_var: false
model:
    model_type: densenet121_metric
    pretrained: true
optimizer: 
<<<<<<< HEAD
    optim_type: adam
    lr: 0.0001
=======
    optim_type: rmsprop
    lr: 0.1
>>>>>>> efdd482551a4eeecf2584eeec0dce76efe31bc9f
scheduler:
    scheduler_type: cosine
sampler:
    sampler_type: random
split: 
    split_type: cskf
    split_num: 5
augment:
    - horizontalflip
    - randomrotate90
